### ISSUE TITLE
raise error when starting optimization

### ISSUE THREAD

**Issue by leepp15** [maria-korosteleva/Body-Shape-Estimation#1]
Hello maria, thanks for your wonderful job. I have configured the program before optimization. The results of takephotos and openpose are normal. When I start to optimize, I find the value of **distance_to_use**   is empty, so after running the code "residuals[i] = residual_elem_(distance_to_use.signedDists(i),distance_to_use.verts_normals.row(i), input_face_normals.row(distance_to_use.closest_face_ids(i)));". The code raises the error because the size of distance_to_use is 0. How can I deal with the problem? Should I set value to distance_to_use manually? Thank you!

**Comment by maria-korosteleva** [comment]
Hello, @lszh2015
Thank you for your interest in my work.

Normally, distance_to_use is assigned the last_result_, which is filled out on the pre-evaluation stage of each optimization step. Ceres-solver calls AbsoluteDistanceBase::PrepareForEvaluation(..)

I've never run into the problem you describe, but let me try to help you figure it out. Could you share your input and the results of openpose (all in the OP_guesses/ subfolder)?

**Comment by leepp15** [comment]
It seems that I have not called the AbsoluteDistanceBase::PrepareForEvaluation(..). But I don't know how to initialize with the function. The link of input and openpose package is [(https://1drv.ms/u/s!ApFTBeE8bvvIb-XlvkCYxwFEuaw?e=IvdIfq)]. Sincerely thanks for your help!

**Comment by leepp15** [comment]
By the way, may I ask what’s the average fitting error in this edition?

**Comment by maria-korosteleva** [comment]
The function AbsoluteDistanceBase::PrepareForEvaluation(..) is intended to be used by Ceres-solver (as  [evaluation callback](http://ceres-solver.org/nnls_solving.html#evaluationcallback)). Before calling this function, Ceres pushes the values of the parameters to the state of smpl object. (AbsoluteDistanceBase->smpl_->state_->..). This is the same smpl object that is passed to AbsoluteDistanceBase object in the constructor. 

Could you clarify, are you trying to call function evaluation (AbsoluteDistanceBase::Evaluate()) directly?

Regarding your second question, we don't have such statistics at the moment

**Comment by leepp15** [comment]
Sorry I haven't tried to call  (AbsoluteDistanceBase::Evaluate())  directly. I configure with the commit edition e9ecd5 and haven't edited the code which is after openpose. I only configure the code in Release mode so the debug is somehow, difficult. Could you find out something in the results I provided? Thank you!

**Comment by leepp15** [comment]
What's more, could you please provide a pair of input mesh and output smpl model?

**Comment by maria-korosteleva** [comment]
Ok, so I tried to run the version after the e9ecd5 commit on my computer and it doesn't crash. 
I attach the full output, you can refer to it as an example you requested: 
[Example output.zip](https://github.com/maria-korosteleva/Body-Shape-Estimation/files/4062663/Example.output.zip).
(In this case, the initial pose estimation from OpenPose was quite bad, so the results are not impressive either. )

One guess that I have regarding your issue is that the ceres-solver might not be working as expected. Please, make sure that the library is installed correctly, and it's working on simple examples. I also provided some notes on installation in ReadMe file (Tips for installing Ceres):
https://github.com/maria-korosteleva/Body-Shape-Estimation/blob/master/README.md

**Comment by maria-korosteleva** [comment]
There were no updated on this issue for some time
Please, re-open the issue if the error persists
